---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: lansible/home-assistant
    build_args:
      - VERSION=${DRONE_TAG:-dev}
      # First line is bare minimum
      - "COMPONENTS=frontend|recorder|http\
                      |discovery\
                      |mobile_app\
                      |mqtt\
                      |buienradar\
                      |denonavr\
                      |androidtv\
                      |opentherm_gw\
                      |flux\
                      |telegram_bot"
      - OTHER=auth.mfa_modules.totp
    tags: ${DRONE_TAG:-dev}-amd64

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: lansible/home-assistant
    build_args:
      - VERSION=${DRONE_TAG:-dev}
      # First line is bare minimum
      - "COMPONENTS=frontend|recorder|http\
                      |discovery\
                      |mobile_app\
                      |mqtt\
                      |buienradar\
                      |denonavr\
                      |androidtv\
                      |opentherm_gw\
                      |flux\
                      |telegram_bot"
      - OTHER=auth.mfa_modules.totp
    tags: ${DRONE_TAG:-dev}-arm64

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-versioned
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    target: lansible/home-assistant:${DRONE_TAG:-dev}
    template: lansible/home-assistant:${DRONE_TAG:-dev}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

- name: manifest-latest
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    target: lansible/home-assistant:latest
    template: lansible/home-assistant:${DRONE_TAG:-dev}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
  when:
    event:
    - tag

depends_on:
- amd64
- arm64
