---
variables:
  DOCKER_IMAGE_NAME: lansible/home-assistant
  BUILD_ARGS:
    "--build-arg COMPONENTS=frontend|recorder|http\
      |discovery\
      |mobile_app\
      |cloud\
      |mqtt\
      |buienradar\
      |denonavr\
      |androidtv\
      |opentherm_gw\
      |ssdp \
      |image \
    --build-arg OTHER=auth.mfa_modules.totp"

include:
  - template: Container-Scanning.gitlab-ci.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/docker-login.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/docker-build.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/sast-cis-benchmark.yml

stages:
  - lint
  - build
  - test
  - push
  - manifest
