---
dist: xenial
language: minimal

env:
  global:
    - fast_finish: true
    - DOCKER_NAMESPACE=lansible
    - CONTAINER_NAME=home-assistant
    # First line is bare minimum
    # netdisco: Needed for discovery
    # paho: Needed for mqtt
    # pydispatch: Needed for zwave
    - "PLUGINS=frontend|pyotp|PyQRCode|sqlalchemy|aiohttp_cors\
                |netdisco\
                |paho\
                |buienradar"

services:
  - docker

matrix:
  include:
    # amd64
    - env: VERSION=${TRAVIS_TAG:-0.91.4} ARCH=amd64

    # arm64
    - env: VERSION=${TRAVIS_TAG:-0.91.4} ARCH=arm64

    # i386
    - env: VERSION=${TRAVIS_TAG:-0.91.4} ARCH=386

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # Pipe to true since the tag could be non existing
  - docker pull ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${VERSION}-${ARCH} || true
  - docker pull ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:latest || true

script:
  # Needed for naming difference between manifest-tool and Alpine multiarch image
  - if [ "${ARCH}" == '386' ]; then
      ALPINE_ARCH=i386;
    else
      ALPINE_ARCH="${ARCH}";
    fi
  # Build homeassistant container
  - docker build .
      --build-arg ARCH=${ALPINE_ARCH}
      --build-arg VERSION=${VERSION}
      --build-arg PLUGINS=${PLUGINS}
      --cache-from ${DOCKER_NAMESPACE}dump/${CONTAINER_NAME}:latest
      --cache-from ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${VERSION}-${ARCH}
      --tag ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${VERSION}-${ARCH}

#TODO: Write a test stage

deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
    tags: true
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: never
