---
dist: xenial
language: minimal

env:
  global:
    - fast_finish: true
    - DOCKER_NAMESPACE=lansible
    - CONTAINER_NAME=home-assistant
    - PLUGINS="frontend|pyotp|PyQRCode|sqlalchemy|aiohttp_cors|buienradar"

services:
  - docker

matrix:
  include:
    # amd64
    - env: HOMEASSISTANT_VERSION=0.90.2 ARCH=amd64
    - env: HOMEASSISTANT_VERSION=0.91.0 ARCH=amd64

    # arm64
    - env: HOMEASSISTANT_VERSION=0.90.2 ARCH=arm64
    - env: HOMEASSISTANT_VERSION=0.91.0 ARCH=arm64

    # i386
    - env: HOMEASSISTANT_VERSION=0.90.2 ARCH=i386
    - env: HOMEASSISTANT_VERSION=0.91.0 ARCH=i386

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # Pipe to true since the tag could be non existing
  - docker pull ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${HOMEASSISTANT_VERSION}-${ARCH} || true
  - docker pull ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${HOMEASSISTANT_VERSION}-${ARCH}-builder || true

script:
  # Build and push builder for faster image builds
  # https://github.com/moby/moby/issues/3471
  - docker build .
      --target builder
      --build-arg ARCH=${ARCH}
      --build-arg VERSION=${HOMEASSISTANT_VERSION}
      --build-arg PLUGINS=${PLUGINS}
      --cache-from ${DOCKER_NAMESPACE}dump/${CONTAINER_NAME}:${HOMEASSISTANT_VERSION}-${ARCH}-builder
      --tag ${DOCKER_NAMESPACE}dump/${CONTAINER_NAME}:${HOMEASSISTANT_VERSION}-${ARCH}-builder
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker push ${DOCKER_NAMESPACE}dump/${CONTAINER_NAME}

  # Build homeassistant container
  - docker build .
      --build-arg ARCH=${ARCH}
      --build-arg VERSION=${HOMEASSISTANT_VERSION}
      --cache-from ${DOCKER_NAMESPACE}dump/${CONTAINER_NAME}:builder-${ARCH}
      --cache-from ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${HOMEASSISTANT_VERSION}-${ARCH}
      --tag ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${HOMEASSISTANT_VERSION}-${ARCH}

#TODO: Write a test stage

deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: never
