---
image: lansible/homeassistant:0.90.2
tags:
  - latest
manifests:
  - image: lansible/homeassistant:0.90.2-amd64
    platform:
      architecture: amd64
      os: linux
  - image: lansible/homeassistant:0.90.2-arm64
    platform:
      architecture: arm64
      os: linux
  - image: lansible/homeassistant:0.90.2-i386
    platform:
      architecture: '386'
      os: linux
