---
version: "3.7"
services:
  homeassistant:
    image: lansible/home-assistant:latest
    ports:
     - "8123:8123"
    volumes:
     - ./config:/config
     - hass-data:/data
  
  postgres:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=hass
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=home_assistant_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata

volumes:
  hass-data:
  pg-data:
